const db = require("./schema");

const seedDatabase = () => {
  const products = [
    {
      name: "Wireless Headphones",
      price: 2999,
    },
    {
      name: "Smart Watch",
      price: 4999,
    },
    {
      name: "Running Shoes",
      price: 3499,
    },
    {
      name: "Travel Backpack",
      price: 1999,
    },
  ];

  const videos = [
    {
      productIndex: 0,
      title: "Wireless Headphones Product Demo",
      videoUrl: "https://example.com/videos/headphones-demo.mp4",
    },
    {
      productIndex: 0,
      title: "Why These Headphones Are Perfect for Travel",
      videoUrl: "https://example.com/videos/headphones-travel.mp4",
    },
    {
      productIndex: 1,
      title: "Smart Watch Features Overview",
      videoUrl: "https://example.com/videos/smartwatch-demo.mp4",
    },
    {
      productIndex: 2,
      title: "Running Shoes Performance Test",
      videoUrl: "https://example.com/videos/running-shoes.mp4",
    },
    {
      productIndex: 3,
      title: "Travel Backpack Capacity Demo",
      videoUrl: "https://example.com/videos/backpack-demo.mp4",
    },
  ];

  const insertProduct = db.prepare(`
    INSERT INTO Products (name, price)
    VALUES (?, ?)
  `);

  const insertVideo = db.prepare(`
    INSERT INTO Videos (product_id, video_url, title)
    VALUES (?, ?, ?)
  `);

  const insertEvent = db.prepare(`
    INSERT INTO EngagementEvents (video_id, event_type)
    VALUES (?, ?)
  `);

  const seed = db.transaction(() => {
    // Delete child records before parent records because of foreign keys
    db.exec(`
      DELETE FROM EngagementEvents;
      DELETE FROM Videos;
      DELETE FROM Products;
    `);

    // Store the actual IDs generated by SQLite
    const productIds = [];

    products.forEach((product) => {
      const result = insertProduct.run(product.name, product.price);

      productIds.push(result.lastInsertRowid);
    });

    // Store the actual IDs generated for videos
    const videoIds = [];

    videos.forEach((video) => {
      const result = insertVideo.run(
        productIds[video.productIndex],
        video.videoUrl,
        video.title
      );

      videoIds.push(result.lastInsertRowid);
    });

    const eventData = [
      { videoIndex: 0, eventType: "view", count: 120 },
      { videoIndex: 0, eventType: "click", count: 45 },
      { videoIndex: 0, eventType: "add_to_cart", count: 18 },

      { videoIndex: 1, eventType: "view", count: 85 },
      { videoIndex: 1, eventType: "click", count: 20 },
      { videoIndex: 1, eventType: "add_to_cart", count: 8 },

      { videoIndex: 2, eventType: "view", count: 150 },
      { videoIndex: 2, eventType: "click", count: 60 },
      { videoIndex: 2, eventType: "add_to_cart", count: 25 },

      { videoIndex: 3, eventType: "view", count: 95 },
      { videoIndex: 3, eventType: "click", count: 30 },
      { videoIndex: 3, eventType: "add_to_cart", count: 12 },

      { videoIndex: 4, eventType: "view", count: 70 },
      { videoIndex: 4, eventType: "click", count: 15 },
      { videoIndex: 4, eventType: "add_to_cart", count: 5 },
    ];

    eventData.forEach(({ videoIndex, eventType, count }) => {
      const videoId = videoIds[videoIndex];

      for (let i = 0; i < count; i++) {
        insertEvent.run(videoId, eventType);
      }
    });
  });

  seed();

  console.log("Database seeded successfully");
};

seedDatabase();